@ECHO OFF
SET SHADER_SOURCE_DIR=%1
SET SHADER_COMPILER=%2
SET SHADER_BINARY_DIR=shaders

IF NOT EXIST "%SHADER_BINARY_DIR%\" MKDIR "%SHADER_BINARY_DIR%"

SET BUILD_DIR=%cd%
CD %SHADER_SOURCE_DIR%
FOR %%F IN (*.comp) DO (
    %SHADER_COMPILER% -V "%%F" -o "%%F.spv"
)
MOVE *.spv "%BUILD_DIR%\%SHADER_BINARY_DIR%" >NUL 2>&1
